INSERT INTO ingredientes (id, nombre) VALUES (1, 'Tallarines de arroz'), (2, 'Pechuga de pollo'), (3, 'Salsa de soja'), (4, 'Cacahuetes'), (5, 'Huevo'), (6, 'Langostinos'), (7, 'Harina de trigo'), (8, 'Leche de vaca'), (9, 'Queso parmesano'), (10, 'Carne picada de ternera'), (11, 'Tomate triturado'), (12, 'Lechuga'), (13, 'Pan de hamburguesa'), (14, 'Arroz arborio'), (15, 'Setas variadas'), (16, 'Garbanzos'), (17, 'Tahini'), (18, 'Salmón fresco'), (19, 'Aguacate'), (20, 'Tortillas de maíz');

INSERT INTO alergenos (id, nombre) VALUES (1, 'Gluten'), (2, 'Crustáceos'), (3, 'Huevos'), (4, 'Pescado'), (5, 'Cacahuetes'), (6, 'Soja'), (7, 'Lácteos'), (8, 'Granos de sésamo');

INSERT INTO recetas (id, nombre, descripcion, tiempo_preparacion) VALUES (1, 'Pad Thai de Pollo', 'Fideos de arroz salteados con pollo, huevo, brotes y cacahuetes.', '25 min'), (2, 'Lasaña Boloñesa Clásica', 'Capas de pasta con salsa de carne, bechamel casera y queso derretido.', '60 min'), (3, 'Risotto de Setas salvajes', 'Arroz cremoso italiano cocinado a fuego lento con variedad de setas.', '35 min'), (4, 'Hamburguesa Gourmet', 'Medallón de ternera con queso, lechuga y salsa especial en pan tierno.', '15 min'), (5, 'Hummus de Garbanzo Casero', 'Crema suave de garbanzos, tahini, limón, aceite de oliva y un toque de comino.', '10 min'), (6, 'Tacos de Salmón y Aguacate', 'Tortillas de maíz rellenas de salmón a la plancha, aguacate y cilantro.', '20 min'), (7, 'Wok de Langostinos', 'Salteado rápido de langostinos con verduras frescas y salsa de soja.', '15 min'), (8, 'Tortilla de Patatas Tradicional', 'La receta clásica española con huevos camperos, patatas y cebolla.', '30 min'), (9, 'Crema de Calabaza y Queso', 'Puré fino de calabaza asada con un toque de queso crema suave.', '25 min'), (10, 'Bowl de Arroz y Pollo Teriyaki', 'Base de arroz con pollo caramelizado en salsa teriyaki casera.', '25 min');

INSERT INTO receta_alergeno (receta_id, alergeno_id) VALUES (1, 3), (1, 5), (1, 6), -- Pad Thai (Huevo, Cacahuete, Soja)(2, 1), (2, 7),         -- Lasaña (Gluten, Lácteos)(3, 7),                 -- Risotto (Lácteos)(4, 1), (4, 7),         -- Hamburguesa (Gluten, Lácteos)(5, 8),                 -- Hummus (Sésamo)(6, 4),                 -- Tacos (Pescado)(7, 2), (7, 6),         -- Wok (Crustáceos, Soja)(8, 3);                 -- Tortilla (Huevos)

INSERT INTO receta_ingrediente (receta_id, ingrediente_id) VALUES (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), -- Pad Thai(2, 7), (2, 8), (2, 9), (2, 10), (2, 11), -- Lasaña(3, 9), (3, 14), (3, 15),                 -- Risotto(4, 9), (4, 10), (4, 12), (4, 13),        -- Hamburguesa(5, 16), (5, 17),                         -- Hummus(6, 18), (6, 19), (6, 20),                -- Tacos(7, 3), (7, 6),                           -- Wok(8, 5),                                   -- Tortilla(9, 8), (9, 9),                           -- Crema Calabaza(10, 2), (10, 3), (10, 14);               -- Bowl Teriyaki
